#!/bin/bash
# auto-generated by /home/xlshen/scratch/shell_script/bash_env/setup.sh:31
# init path : /home/xlshen/scratch/shell_script/bash_env/init/script_path_config.sh
# It contains the path configuration for bash environment.

EXT_DIR="/home/xlshen/scratch"
BASH_DIR="/home/xlshen/scratch/shell_script/bash_env"
TEMP_DIR="/home/xlshen/scratch/tmp"
BACKUP_DIR="/home/xlshen/scratch/backup"
CACHE_DIR="/home/xlshen/scratch/cache"
TEST_DIR="/home/xlshen/scratch/test"
DEPENDENCY_DIR="/home/xlshen/scratch/third_part_dependency"

