#!/bin/bash
# auto-generated by /home/xlshen/scratch/bash_env/setup.sh:31
# init path : /home/xlshen/scratch/bash_env/init/script_path_config.sh
# It contains the path configuration for bash environment.
[[ ! -v disable_bash_script_io ]] && echo -e "# +++++++++ loading ${BASH_SOURCE[0]}:${LINENO}  \e[0;30m:  ${BASH_SOURCE[1]##*/}:${BASH_LINENO[0]} \e[0;0m" 

export EXT_DIR="/home/xlshen/scratch"
export BASH_DIR="/home/xlshen/scratch/bash_env"
export TEMP_DIR="/home/xlshen/scratch/tmp"
export BACKUP_DIR="/home/xlshen/scratch/backup"
export CACHE_DIR="/home/xlshen/scratch/cache"
export TEST_DIR="/home/xlshen/scratch/test"
export DEPENDENCY_DIR="/home/xlshen/scratch/third_part_dependency"

[[ ! -v disable_bash_script_io ]] && echo -e "# --------- leaving ${BASH_SOURCE[0]}:${LINENO}  "
